More AutoReplies
Aliucord/Aliucord-backend pull request #19
Opened 2022-08-11 16:24 UTC by OmegaSunkey

2023-10-01 16:52 UTC, OmegaSunkey commented
Made some fixes. I'll wait for review.

2023-10-01 17:03 UTC, rushiiMachine commented on bot/modules/auto_replies.go
> +	FreeNitro        = "Not possible. Nitrospoof exists for \"free\" emotes, UserBG exists for using a custom banner (read the plugin's description), UserPFP exists for using a custom banner (read the d
> UserPFP exists for using a custom banner

?

2023-10-01 17:03 UTC, rushiiMachine commented on bot/modules/auto_replies.go
> +		//r("where(?: i)s(?: the)? plugin ?downloader"):  PluginDownloader,
i think we still need this
people occasionally still ask

2023-10-01 17:05 UTC, OmegaSunkey commented on bot/modules/auto_replies.go
> +		//r("where(?: i)s(?: the)? plugin ?downloader"):  PluginDownloader,
ok readding

2023-10-01 17:12 UTC, OmegaSunkey commented
pushed changes

2023-10-01 17:59 UTC, rushiiMachine requested changes

2023-10-01 17:59 UTC, rushiiMachine commented on bot/modules/auto_replies.go
> +		r("(?:where|how) (?:to|do i|do you) (?:install|download|get) (?:a?.?plugins?)"):                	         	  InstallPlugins,
```suggestion
		r("(?:where|how) (?:to|do i|do you) (?:install|download|get) a? ?plugins?"):                	         	  InstallPlugins,
```

2023-10-01 17:59 UTC, rushiiMachine commented on bot/modules/auto_replies.go
> +		r("how (?:to|do i|do you|i) (?:install|download|apply|get|use) (?:a?.?themes?)"):                     	    	  InstallThemes,
```suggestion
		r("how (?:to|do i|do you|i) (?:install|download|apply|get|use) a? ?themes?"):                     	    	  InstallThemes,
```

2023-10-01 17:59 UTC, rushiiMachine commented on bot/modules/auto_replies.go
> +		r("how (?:to|do i|do you|can i) (?:create|make|do) (?:a theme|(my own |a?.?custom )?themes?)"):             	  CreateThemes,
```suggestion
		r("how (?:to|do i|do you|can i) (?:create|make|do) (?:a|my own)? ?(?:custom)? ?themes?"):             	  CreateThemes,
```

2023-10-01 17:59 UTC, rushiiMachine commented on bot/modules/auto_replies.go
> +		r("(does anyone know|is there) an? (\w.+)?theme"):                                                                SearchThemes,
```suggestion
		r("(?:does anyone know|is there) an? (?:\w.+)?theme"):                                                                SearchThemes,
```

2023-10-01 17:59 UTC, rushiiMachine commented on bot/modules/auto_replies.go
> +		r("(my )?aliucord (\w.+)?(?:crashed|keeps crashing|crash|crashes|is crashing|crashing|stopped( working)?)"):      AliuCrash,
```suggestion
		r("(?:my )?aliucord (?:\w.+)?(?:crashed|keeps crashing|crash|crashes|is crashing|crashing|stopped(?: working)?)"):      AliuCrash,
```

2023-10-01 17:59 UTC, rushiiMachine commented on bot/modules/auto_replies.go
> +		r("(why |with )?(?:is )?full transparency (?:is?.?not|will not|doesn\\'t|does not) (?:work)"):                     FullTransparency,
```suggestion
		r("(?:why |with )?(?:is )?full transparency (?:is?.?not|will not|doesn\\'t|does not) (?:work)"):                     FullTransparency,
```

2023-10-02 06:13 UTC, rushiiMachine approved these changes

2023-10-20 17:06 UTC, Juby210 approved these changes

2023-10-20 17:06 UTC, merged