added full transparency, tutorial (not shitpost) for themer and more …
Aliucord/Aliucord-backend pull request #9
Opened 2021-12-29 15:07 UTC by OmegaSunkey

…rege x

I DONT know how to use regex p

2021-12-29 15:17 UTC, DiamondMiner88 requested changes

2021-12-29 15:17 UTC, DiamondMiner88 commented on bot/modules/auto_replies.go
> +		r("(my aliucord|aliucord) (crashed|keeps crashing|crash|crashes)"):      AliuCrash,
```suggestion
		r("(?:my )?aliucord (?:crashed|keeps crashing|crash|crashes)"):      AliuCrash,
```

2021-12-29 15:17 UTC, DiamondMiner88 commented on bot/modules/auto_replies.go
> +		r("^(why|with) full transparency (is not|not|will not) (work|working)"): FullTransparency,
```suggestion
		r("^(?:why|with) (?:is )?full transparency (?:is not|not|will not) (work|working)"): FullTransparency,
```

2022-01-01 16:27 UTC, OmegaSunkey commented
merge when

2022-01-09 22:34 UTC, merged